# Generated by Django 4.2.17 on 2024-12-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
    ]
